Slave1
AnastasiaSerenko/Serenko_lesson2 pull request #1
Opened 2020-04-26 13:06 UTC by AnastasiaSerenko

lesson2: create first page - "header"

2020-04-27 07:12 UTC, studenttsu commented
Названия папок проекта принято называть с маленькой буквы. 
Имя главной html-страницы принято называть index.html.

2020-04-27 07:38 UTC, studenttsu commented
Имени PR лучше давать названия в соответствие с содержимым реквеста. В данном случае это могло бы быть `Layout for header` (вёрстка шапки)

2020-05-04 13:02 UTC, studenttsu requested changes

2020-05-04 13:02 UTC, studenttsu commented on lesson2.html
> +                    <divs>
divs - несуществующий тег

2020-05-04 13:02 UTC, studenttsu commented on lesson2.html
> +                <div class="head_top">
Для разделения слов в именах классов используется одиночное тире `head-top`. Для задания имени класса элемента блока по [БЭМ](https://ru.bem.info/methodology/naming-convention/), используется двойное подчёркивание `head__top`

2020-05-04 13:02 UTC, studenttsu commented on lesson2.html
> +                    <div  class="head_top_img">
Обычно логотип - это независимый блок на странице, его мы можем переиспользовать во многих местах. Соответственно в данном случае лучше использовать имя `logo`. Так логотип сайта используется как ссылка на главную страницу, поэтому его лучше завернуть в тег ссылки `a`

```
<a href="/" class="logo">
  <img src="Images/WD.png" alt="WD">
</a>
```

2020-05-04 13:02 UTC, studenttsu commented on lesson2.html
> +                    <img src="Images/Frame.png" alt="WD" class="head_down_img">
для большей гибкости позиционирования, лучше картинку завернуть в div и уже относительно этого div позиционировать картинку внутри контейнера

2020-05-04 13:02 UTC, studenttsu commented on lesson2.html
> +                 <div class="head_down">
по поводу именования элементов блока писал выше

2020-05-04 13:02 UTC, studenttsu commented on lesson2.html
> +                        <span>
для какой цели параграф заворачиваешь в span?

2020-05-04 13:02 UTC, studenttsu commented on lesson2.html
> +                <a name = "head"></a>
Обычно атрибут тега не отделяют пробелами от его значения. Лучше придерживаться одного стиля написания кода для всех тегов

`<a name="head"></a>`

2020-05-04 13:02 UTC, studenttsu commented on Fonts/roboto/roboto.css
> +@font-face {
Очень хорошо, что удалось разобраться с подключением шрифтов разных типов

2020-05-04 13:02 UTC, studenttsu commented on Images/roboto/roboto.css
> +@font-face {
зачем в Images появились шрифты?

2020-05-04 13:02 UTC, studenttsu commented on style.css
> +    height: 693px;
не стоит указывать фиксированное значения для высоты, ведь контент в будущем будет наполняться и высота страницы будет увеличиваться

2020-05-04 13:02 UTC, studenttsu commented on style.css
> +
Старайся не оставлять пустые строки без надобности. В vscode можно нажать сочетание клавишь Shift+Alt+F и эта команда автоматически отформатирует код

2020-05-04 14:30 UTC, studenttsu requested changes

2020-05-04 14:30 UTC, studenttsu commented on index.html
> +                    <h1 class="head-down__content__title">Дизайн и верстка</h1>
Элементы могут быть только у блоков, почитай подробнее тут:
https://ru.bem.info/methodology/quick-start/#%D0%BF%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF%D1%8B-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%D0%B8

2020-05-04 14:30 UTC, studenttsu commented on index.html
> +                    <button>НАПИСАТЬ МНЕ</button>
Не принято писать текст "капсом". Лучше стилизовать с помощью text-transform: uppercase. Так более универсально.

В будущем дизайнеру может придти в голову, что текст кнопок должен начинаться с большой буквы. Чтобы сделать изменения тебе будет достаточно изменить одно правило в css, а не бегать по всем кнопкам в разметке и переименовывать.

2020-05-04 17:00 UTC, AnastasiaSerenko commented on index.html
> +                    <h1 class="head-down__content__title">Дизайн и верстка</h1>
В третий раз кажется, что поняла

2020-05-04 17:19 UTC, AnastasiaSerenko commented on lesson2.html
> +                        <span>
Где-то увидела, что его используют для текстов, но не разобралась. Сейчас почитала. Не нужен здесь

2020-05-05 10:24 UTC, studenttsu approved these changes

2020-05-05 10:30 UTC, merged